/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/moreInfo/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/data`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/Map`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/patientInfoModal`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/patientsList`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/route`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/moreInfo/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/data`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/Map`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/patientInfoModal`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/patientsList`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/route`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/paramedic/types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/paramedic/moreInfo/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/onboarding/login${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | `/paramedic/dashboard${`?${string}` | `#${string}` | ''}` | `/paramedic/data${`?${string}` | `#${string}` | ''}` | `/paramedic/Map${`?${string}` | `#${string}` | ''}` | `/paramedic/patientInfoModal${`?${string}` | `#${string}` | ''}` | `/paramedic/patientsList${`?${string}` | `#${string}` | ''}` | `/paramedic/route${`?${string}` | `#${string}` | ''}` | `/paramedic/scanner${`?${string}` | `#${string}` | ''}` | `/paramedic/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/moreInfo/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/data`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/Map`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/patientInfoModal`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/patientsList`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/route`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/paramedic/types`; params?: Router.UnknownInputParams; };
    }
  }
}
